FileVersion = 1
Dependencies = {corlib = "*", BeefToml = "*", CowieCLI = "*"}

[Project]
Name = "Grill"
StartupObject = "Grill.Program"

[Platform.Windows]
FileVersion = "0.0.1"
ProductVersion = "0.0.1"

[Configs.Debug.Win64]
BeefLibType = "Static"
BuildCommandsOnCompile = "Never"
BuildCommandsOnRun = "Never"
PostBuildCmds = ["xcopy \"$(ProjectDir)/bin\" \"$(TargetDir)\" /e /c /i /q /y"]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Debug.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Release.Win64]
BuildCommandsOnCompile = "Never"
BuildCommandsOnRun = "Never"
PostBuildCmds = ["xcopy \"$(ProjectDir)/bin\" \"$(TargetDir)\" /e /c /i /q /y"]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Release.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Paranoid.Win64]
BuildCommandsOnCompile = "Never"
BuildCommandsOnRun = "Never"
PostBuildCmds = ["xcopy \"$(ProjectDir)/bin\" \"$(TargetDir)\" /e /c /i /q /y"]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Paranoid.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Test.Win64]
BuildCommandsOnCompile = "Never"
BuildCommandsOnRun = "Never"
PostBuildCmds = ["xcopy \"$(ProjectDir)/bin\" \"$(TargetDir)\" /e /c /i /q /y"]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs.Test.Win32]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill add".Win64]
BeefLibType = "Static"
BuildCommandsOnCompile = "Never"
BuildCommandsOnRun = "Never"
PostBuildCmds = ["xcopy \"$(ProjectDir)/bin\" \"$(TargetDir)\" /e /c /i /q /y"]
DebugCommandArguments = "add steak.logging -debug"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill add".Win32]
BeefLibType = "Static"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill install".Win64]
BeefLibType = "Static"
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "Never"
PostBuildCmds = ["xcopy \"$(ProjectDir)/bin\" \"$(TargetDir)\" /e /c /i /q /y", "del /F/Q/S \"$(TargetDir)/Packages\" >NULL", "echo test"]
DebugCommandArguments = "install mypackage --debug"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS", "DEBUG"]

[Configs."grill install".Win32]
BeefLibType = "Static"
PostBuildCmds = ["xcopy \"$(ProjectDir)/bin\" \"$(TargetDir)\" /e /c /i /y", "del /F/Q/S \"$(TargetDir)/Packages\" >NULL"]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill --help".Win64]
BeefLibType = "Static"
BuildCommandsOnCompile = "Never"
BuildCommandsOnRun = "Never"
PostBuildCmds = ["xcopy \"$(ProjectDir)/bin\" \"$(TargetDir)\" /e /c /i /q /y"]
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]

[Configs."grill --help".Win32]
BeefLibType = "Static"
PreprocessorMacros = ["GRILL_PLATFORM_WINDOWS"]
