FileVersion = 1
Projects = {Grill = {Path = "."}, CowieCLI = {Path = "../CowieCLI"}}

[Workspace]
StartupProject = "Grill"

[Configs."grill add".Win32]
ConfigSelections = {Grill = {Config = "Debug"}}

[Configs."grill install".Win32]
ConfigSelections = {Grill = {Config = "Debug"}}

[Configs."grill --help".Win32]
ConfigSelections = {Grill = {Config = "Debug"}}

[Configs.Release.Win64]
AllocType = "Debug"
