FileVersion = 1
LastConfig = "grill --help"
LastPlatform = "Win64"
RecentFilesList = ["c:\\dev\\Beef\\Grill\\src\\CLI\\CLI.bf", "c:\\dev\\Beef\\Grill\\src\\Program.bf", "c:\\dev\\Beef\\Grill\\src\\CLI\\InstallCommand.bf", "c:\\dev\\Beef\\Grill\\src\\CLI\\AddCommand.bf"]

[MainWindow]
X = 64
Y = 16
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 308.0
RequestedHeight = 309.0
SizePriority = 308.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 264.0
RequestedHeight = 309.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 116.3265
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 829.0
RequestedHeight = 461.0
SizePriority = 829.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "CLI.bf"
TabWidth = 62.65306
Type = "SourceViewPanel"
FilePath = "c:\\dev\\Beef\\Grill\\src\\CLI\\CLI.bf"
CursorPos = 3995
VertPos = 2280.0
ProjectName = "Grill"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 97.34694
Type = "SourceViewPanel"
FilePath = "c:\\dev\\Beef\\Grill\\src\\Program.bf"
CursorPos = 233
ProjectName = "Grill"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 785.0
RequestedHeight = 309.04
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 785.0
RequestedHeight = 309.0
SizePriority = 1918.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Errors"
TabWidth = 86.7347
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.7347
Type = "WatchPanel"
Columns = [{Width = 182.0}, {Width = 182.0}, {Width = 182.0}]
Items = ["WorkspaceStartupProject", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 100.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.55102
Type = "AutoWatchPanel"
Columns = [{Width = 182.0}, {Width = 260.0}, {Width = 182.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 1918.0
RequestedHeight = 309.0
SizePriority = 1918.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.81632
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 106.1224
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.95918
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 112.2449
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 120.4082
Type = "FindResultsPanel"

[DebuggerDisplayTypes.""]
IntDisplayType = "Default"
MmDisplayType = "Default"
